-- AlterEnum
ALTER TYPE "TicketEventType" ADD VALUE IF NOT EXISTS 'AI_ANALYZED';
ALTER TYPE "TicketEventType" ADD VALUE IF NOT EXISTS 'AI_SUGGESTED';
ALTER TYPE "TicketEventType" ADD VALUE IF NOT EXISTS 'AI_DRAFTED';
ALTER TYPE "TicketEventType" ADD VALUE IF NOT EXISTS 'AI_CHATTED';
ALTER TYPE "TicketEventType" ADD VALUE IF NOT EXISTS 'AI_FEEDBACK';
